# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('geonameid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('feature_code', models.CharField(max_length=15)),
                ('population', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ('name', 'country'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('legal_name', models.CharField(blank=True, max_length=100)),
                ('cif', models.CharField(blank=True, max_length=25)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('official_company', models.BooleanField(default=True, help_text='Official company in Nubelo, in case of duplicates')),
                ('fee', models.CharField(blank=True, max_length=25)),
                ('nubelo_id', models.IntegerField(blank=True, null=True)),
                ('nubelo_url', models.URLField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('n/a', 'N/A')], max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_companies', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='crm.City')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CompanyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('phone_call', 'Phone call'), ('meeting', 'Meeting'), ('email', 'Email'), ('proposal_sent', 'Proposal Sent'), ('proposal_signed', 'Proposal Signed'), ('blind_cv', 'Blind CV'), ('other', 'Other')], max_length=25)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='to_do', max_length=25)),
                ('description', models.TextField()),
                ('blind_cvs_sent', models.IntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, upload_to='uploads/actions/companies/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_timestamp', models.DateTimeField(db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_actions', to='crm.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary_contact',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField()),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('num_vacancies', models.IntegerField(default=1)),
                ('job_type', models.CharField(choices=[('employee', 'Employee'), ('freelance', 'Freelance')], max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.CharField(blank=True, max_length=25)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('document', models.FileField(blank=True, upload_to='uploads/docs/jobs/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nubelo_id', models.IntegerField(blank=True, null=True)),
                ('nubelo_url', models.URLField(blank=True, max_length=250)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='crm.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='crm.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='JobAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('candidates_sent', 'Candidates Sent'), ('client_interviewed_candidate', 'Client Interviewed Candidate'), ('client_made_job_offer', 'Client Made Job Offer'), ('candidate_accepted_offer', 'Candidate Accepted Offer'), ('candidate_rejected_offer', 'Candidate Rejected Offer'), ('other', 'Other')], max_length=25)),
                ('action_num_candidates', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, upload_to='uploads/actions/job/%Y/%m/%d/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_actions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_actions', to='crm.Job')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=31, unique=True)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='crm.Skill'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='crm.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='skills',
            field=models.ManyToManyField(related_name='companies', to='crm.Skill'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='crm.Country'),
        ),
    ]
