# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:07
from __future__ import unicode_literals

from functools import reduce
from operator import or_

from django.db import migrations
from django.db.models import Q


COUNTRIES = (
    ('AR', 'Argentina'),
    ('BR', 'Brazil'),
    ('CO', 'Colombia'),
    ('DE', 'Germany'),
    ('ES', 'Spain'),
    ('FR', 'France'),
    ('GB', 'United Kingdom'),
    ('IT', 'Italy'),
    ('MX', 'Mexico'),
    ('US', 'United States'),
    ('VE', 'Venezuela'),
)


def add_country_data(apps, schema_editor):
    Country = apps.get_model('crm', 'Country')
    country_list = []
    for country_code, name in COUNTRIES:
        country_list.append(Country(country_code=country_code, name=name))
    Country.objects.bulk_create(country_list)


def remove_country_data(apps, schema_editor):
    Country = apps.get_model('crm', 'Country')
    query_list = []
    for country_code, _ in COUNTRIES:
        query_list.append(Q(country_code=country_code))
    query = reduce(or_, query_list)
    Country.objects.filter(query).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_industry_data'),
    ]

    operations = [
        migrations.RunPython(
            add_country_data,
            remove_country_data,
        )
    ]
