# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:28
from __future__ import unicode_literals

import csv
import os

from django.db import migrations


def add_city_data(apps, schema_editor):
    Country = apps.get_model('crm', 'Country')
    City = apps.get_model('crm', 'City')
    dir_name = os.path.dirname(os.path.dirname(__file__))
    file_path = os.path.join(dir_name, 'data')
    with open('{}/es_adm3_top_100.csv'.format(file_path)) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            country = Country.objects.get(country_code=row['country code'])
            city = City.objects.create(
                geonameid=row['geonameid'],
                name=row['name'],
                latitude=row['latitude'],
                longitude=row['longitude'],
                feature_code=row['feature code'],
                country=country,
                population=row['population'])
            city.save()


def remove_city_data(apps, schema_editor):
    City = apps.get_model('crm', 'City')
    dir_name = os.path.dirname(os.path.dirname(__file__))
    file_path = os.path.join(dir_name, 'data')
    with open('{}/es_adm3_top_100.csv'.format(file_path)) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            city = City.objects.get(geonameid=row['geonameid'])
            city.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_country_data'),
    ]

    operations = [
        migrations.RunPython(
            add_city_data,
            remove_city_data,
        )
    ]
