# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_city_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobaction',
            name='title',
        ),
        migrations.AlterField(
            model_name='companyaction',
            name='action',
            field=models.CharField(choices=[('phone_call', 'Phone call'), ('meeting', 'Meeting'), ('email', 'Email'), ('proposal_sent', 'Proposal Sent'), ('proposal_signed', 'Proposal Signed'), ('blind_cv', 'Blind CV'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobaction',
            name='action',
            field=models.CharField(choices=[('candidates_sent', 'Candidates Sent'), ('client_interviewed_candidate', 'Client Interviewed Candidate'), ('client_made_job_offer', 'Client Made Job Offer'), ('candidate_accepted_offer', 'Candidate Accepted Offer'), ('candidate_rejected_offer', 'Candidate Rejected Offer'), ('other', 'Other')], max_length=50),
        ),
    ]
